### ISSUE TITLE
Another plan (Use bat instead of dll hijack)

### ISSUE THREAD

**Issue by kangzq0530** [aiqinxuancai/discord-proxy#1]
```
@echo off
set https_proxy=http://127.0.0.1:1080
set http_proxy=http://127.0.0.1:1080
start Discord.exe --proxy-server=http://127.0.0.1:1080
```

`--a` is used by old Windows version of Discord, and should be removed now.

**Comment by aiqinxuancai** [comment]
This is indeed a good solution as well.
Also --a is for the parameters of update.exe in the parent directory, and the old Discord.exe.

This parameter is obtained by decompiling Update.exe so that Update.exe will pass the parameters after --a when starting Discord.exe.

The --a parameter was found from another of my articles at
https://zhuanlan.zhihu.com/p/47048247
